### PR TITLE
unfinished open core assets [do not merge]

### PR DESCRIPTION
**Pull request by 20kdc**
NOTE: This probably shouldn't be merged directly into it's target, it would be confusing.

This adds a set of open 'core assets' for use of the engine independent of Amnesia: The Dark Descent. There are also some slight code changes to help facilitate debugging of certain errors that can occur with the GUI.

HPL1 assets were imported from https://github.com/FrictionalGames/HPL1Engine to allow this.

I don't think I can go much further without documenting the function of literally every shader in the hope that someone not-me will write workable replacements.

What I've actually replaced the shaders with are bare-minimum operations that technically at least make the graphics appear (usually) but above all else focus on not being a copyright problem.
Same principle applies to the core models.

If someone else has already done this, and ideally in a way that actually functions, then do tell me.

To be clear, my focus here is on that HPL1 "could have" been a usable game engine, but wasn't due to the Newton issues - old Newton was unavailable and new Newton was glitchy because of something all the forks were missing.

If there's an ultimate HPL1 fork that's usable the way your HPL2 fork is, I'd like to know about that too.

### CODE REVIEW

**Comment by pollend** [comment]
that looks pretty interesting! want to replace the rendering backend with something different. was looking at these two libraries: https://github.com/bkaradzic/bgfx and https://github.com/ConfettiFX/The-Forge

**Comment by 20kdc** [comment]
The Forge looks very much like it could wipe out the shader problems entirely (i.e. by using ThE Forge's example shaders), but at a massive cost - massively increasing HPL2's hardware requirements, which seems counter-productive to using HPL2 in the first place.

BGFX doesn't have this problem, but has a different problem: it still needs shaders, and if it's targetting, say, OpenGL ES 2, they can't be imported from Amnesia either.

**Comment by pollend** [comment]
there is some support for older cards for vulkan. most people have a GCN 2 card, not so sure about nvidia but it should be most cards in the last 4 or so years. the abstraction layer that the forge uses does not play well with hpl2 abstraction. it diverges enough where I'm probably going to rewrite the abstraction for shaders and materials and to some extent how meshes work in the core engine. bgfx is a lot more closer to opengl API so maybe it would be a much easier change to make. 

I was planning on reading over this white paper on the weekend: https://eheitzresearch.wordpress.com/415-2/. pretty sure this can be accomplished on bgfx since the base requirements of the engine are not particularly demanding. want to redo some of the lighting for the game.

**Comment by 20kdc** [comment]
"Some support for older cards for Vulkan" is debatable.
It depends what level of "older" is acceptable, especially given raising the hardware requirements of the game for absolutely no receivable benefit whatsoever seems pointless.
Obviously the big one is Intel on Windows, because Intel are *always* late on everything. HPL2 *as-is* barely works on Intel Ironlake with minor shader patches and an OpenGL hook. Any increase in API version or switching to Vulkan makes the game completely unrunnable.
Even OpenGL 3.3 is unreliable - "support" for OpenGL 3.3 doesn't mean it actually works, *especially* on Windows.

**Comment by pollend** [comment]
your changes seem pretty good @20kdc I haven't tested them. ping me when you are ready.

**Comment by 20kdc** [comment]
I don't think the changes are appropriate for the main branch, although if you want to merge them you can do so at any time. The main thing is that the open shaders/models are intended for use in development of new games rather than playing A:TDD.
I filed this as a draft because I figure it would be good for an alternate branch.
Of course ultimately this is down to your policy - if you want me to mark it ready so you can merge it anyway, just tell me.

**Pull request closed without merging**
